/*
 * This file is generated by jOOQ.
 */
package com.nisarg.database.tables.daos;


import com.nisarg.database.tables.Adrights;
import com.nisarg.database.tables.records.AdrightsRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import javax.annotation.Generated;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class AdrightsDao extends DAOImpl<AdrightsRecord, com.nisarg.database.tables.pojos.Adrights, Integer> {

    /**
     * Create a new AdrightsDao without any configuration
     */
    public AdrightsDao() {
        super(Adrights.ADRIGHTS, com.nisarg.database.tables.pojos.Adrights.class);
    }

    /**
     * Create a new AdrightsDao with an attached configuration
     */
    @Autowired
    public AdrightsDao(Configuration configuration) {
        super(Adrights.ADRIGHTS, com.nisarg.database.tables.pojos.Adrights.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer getId(com.nisarg.database.tables.pojos.Adrights object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.nisarg.database.tables.pojos.Adrights> fetchById(Integer... values) {
        return fetch(Adrights.ADRIGHTS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.nisarg.database.tables.pojos.Adrights fetchOneById(Integer value) {
        return fetchOne(Adrights.ADRIGHTS.ID, value);
    }

    /**
     * Fetch records that have <code>al_id IN (values)</code>
     */
    public List<com.nisarg.database.tables.pojos.Adrights> fetchByAlId(String... values) {
        return fetch(Adrights.ADRIGHTS.AL_ID, values);
    }

    /**
     * Fetch records that have <code>text IN (values)</code>
     */
    public List<com.nisarg.database.tables.pojos.Adrights> fetchByText(String... values) {
        return fetch(Adrights.ADRIGHTS.TEXT, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.nisarg.database.tables.pojos.Adrights> fetchByType(String... values) {
        return fetch(Adrights.ADRIGHTS.TYPE, values);
    }
}
