/*
 * This file is generated by jOOQ.
 */
package com.nisarg.database;


import com.nisarg.database.tables.Adrights;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADRIGHTS_PKEY = Indexes0.ADRIGHTS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ADRIGHTS_PKEY = Internal.createIndex("adrights_pkey", Adrights.ADRIGHTS, new OrderField[] { Adrights.ADRIGHTS.ID }, true);
    }
}
