/*
 * This file is generated by jOOQ.
 */
package com.nisarg.database;


import com.nisarg.database.tables.Adrights;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.adrights</code>.
     */
    public static final Adrights ADRIGHTS = com.nisarg.database.tables.Adrights.ADRIGHTS;
}
